dependencies:
  - name: nuclio
    version: "0.19.15"
    repository: "https://nuclio.github.io/nuclio/charts"
  - name: mlrun
    version: "0.10.0"
    repository: "https://v3io.github.io/helm-charts/stable"
    condition: mlrun.enabled
  - name: mpi-operator
    version: "0.6.0"
    repository: "https://v3io.github.io/helm-charts/stable"
  - name: minio
    repository: "https://charts.min.io/"
    version: "5.2.0"
    condition: minio.enabled
  - name: spark-operator
    repository: "https://kubeflow.github.io/spark-operator"
    version: "1.1.25"
    condition: spark-operator.enabled
  - name: kube-prometheus-stack
    repository: "https://prometheus-community.github.io/helm-charts"
    version: "41.7.2"
    condition: kube-prometheus-stack.enabled
