{{- /*
MinIO credentials secret
Used to avoid exposing credentials in ConfigMaps / UI variables on rerun.
*/ -}}
{{- if and (.Values.minio.enabled) (not .Values.global.infrastructure.aws.s3NonAnonymous) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.minioCredentialsSecretName }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.minio.rootUser | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.rootPassword | b64enc | quote }}
{{- end -}}
